[package]
name = "nvm-rust"
version = "0.0.0"
authors = [ "BeeeQueue <adam.lj.haglund@gmail.com>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
clap = "3.0.0-beta.1"
reqwest = { version = "0.10.8", features = [ "blocking" ] }
semver = { version = "0.11.0", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0.57"

[target."cfg(unix)".dependencies]
flate2 = "1.0.18"
tar = "0.4.30"

[target."cfg(windows)".dependencies]
zip = "0.5.6"

[dev-dependencies]
assert_cmd = "1.0.1"
serial_test = "0.5.0"
