[package]
name = "nvm-rust"
version = "0.1.0"
authors = ["BeeeQueue <adam.lj.haglund@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
reqwest = { version = "0.10.7", features = ["blocking"] }
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.56"

[target.'cfg(unix)'.dependencies]
flate2  = "1.0.16"
tar  = "0.4.29"

[target.'cfg(windows)'.dependencies]
zip = "0.5.6"
