[package]
name = "nvm-rust"
version = "0.2.0"
description = "A node version manager that doesn't suck"
authors = ["BeeeQueue <adam@haglund.dev>"]
repository = "https://github.com/BeeeQueue/nvm-rust"
homepage = "https://github.com/BeeeQueue/nvm-rust"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["node", "version", "manager", "nvm"]
categories = ["command-line-utilities"]
edition = "2021"

exclude = [
  ".github/",
  "tests/",
  "test-data/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.8", features = ["derive", "env", "cargo"] }
dialoguer = "0.10.1"
dirs = "4.0.0"
itertools = "0.10.3"
node-semver = "2.0.0"
reqwest = { version = "0.11.11", features = ["blocking"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"

[target.'cfg(unix)'.dependencies]
flate2 = "1.0.24"
tar = "0.4.38"

[target.'cfg(windows)'.dependencies]
zip = "0.6.2"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
predicates = "2.1.1"
