[package]
name = "nvm-rust"
version = "0.1.0"
authors = ["BeeeQueue <adam@haglund.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
clap = "3.0.0-beta.4"
dirs = "4.0.0"
node-semver = "2.0.0"
reqwest = { version = "0.10.10", features = ["blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"

[target.'cfg(unix)'.dependencies]
flate2  = "1.0.21"
tar  = "0.4.37"

[target.'cfg(windows)'.dependencies]
zip = "0.5.6"

[dev-dependencies]
assert_cmd = "1.0.2"
serial_test = "0.5.1"
