version: 3

tasks:
  lint:
    desc: Lint code
    cmds:
      - cargo clippy
  lint:fix:
    desc: Lint code and fix problems with autofixes
    cmds:
      - cargo clippy --fix --allow-staged --allow-dirty

  format:
    desc: Format code
    cmds:
      - cargo fmt --all

  test:
    desc: Run tests
    sources:
      - Cargo.*
      - src/**
      - test-data/**
      - tests/**
    cmds:
      - cargo test

  run:
    desc: "Run the CLI with a debug build: task run -- <...args>"
    cmds:
      - cargo run

  build:
    desc: Build debug artifacts
    sources:
      - Cargo.*
      - src/**
    generates:
      - target/debug/**
    cmds:
      - cargo build

  build:release:
    desc: Build release artifacts
    sources:
      - Cargo.*
      - src/**
    generates:
      - target/release/**
    cmds:
      - cargo build --release --locked
