on: [ push ]

name: ci

env:
  FORCE_COLOR: 3
  TERM: xterm-256color

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: build

      - run: cargo build --release --all-features --locked

  test:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: test

      - run: cargo test --release --all-features

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
