on: [ push ]

name: ci

env:
  FORCE_COLOR: 3
  TERM: xterm-256color

jobs:
  build:
    name: build (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            file-name: nvm-rust
            display-name: nvm-rust-macos64.exe
          - os: ubuntu-latest
            file-name: nvm-rust
            display-name: nvm-rust-linux64.exe
          - os: windows-latest
            file-name: nvm-rust.exe
            display-name: nvm-rust-win64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.2

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: build

      - run: cargo build --all-features --locked --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: target/release/${{ matrix.file-name }}

  test:
    timeout-minutes: 15
    continue-on-error: true
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.2

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: test

      - run: cargo test --all-features -- --nocapture

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
