name: CI
on: [push]

jobs:
  build_and_test:
    name: Build and Test
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - platform: macos-latest
            binary: target/release/nvm-rust
          - platform: ubuntu-latest
            binary: target/release/nvm-rust
          - platform: windows-latest
            binary: target/release/nvm-rust.exe
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ matrix.os }}-cargo-

      - run: cargo build --release --all-features --locked

      - run: cargo test --release --all-features

      - name: "Upload artifacts"
        #if:
        run: echo "${{ github.ref }}"

      - name: "Log built files"
        #if:
        run: ls target/release

      - name: "Log built files"
        #if:
        run: ls ${{ matrix.binary }}

    
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
