on:
  workflow_dispatch:
  push:
    tags:
      - v*

name: release

env:
  FORCE_COLOR: 3
  TERM: xterm-256color

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v2

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - uses: softprops/action-gh-release@v1
        with:
          draft: true


  build:
    name: build (${{ matrix.os }})

    needs: [create-release]

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            file-name: nvm
            display-name: nvm-macos
          - os: ubuntu-latest
            file-name: nvm
            display-name: nvm-linux
          - os: windows-latest
            file-name: nvm.exe
            display-name: nvm-win.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v2

      - run: task build:release

      - run: mv target/release/${{ matrix.file-name }} target/release/${{ matrix.display-name }}

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: target/release/${{ matrix.display-name }}
