name: Release
on:
  release:
    types:
      - published

jobs:
  upload:
    name: "Build and Upload Artifacts"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        include:
          - platform: macos-latest
            binary: target/release/nvm-rust
            name: nvm
            label: Mac
          - platform: ubuntu-latest
            binary: target/release/nvm-rust
            name: nvm
            label: Linux
          - platform: windows-latest
            binary: target/release/nvm-rust.exe
            name: nvm.exe
            label: Windows

    steps:
      - run: echo "${{ toJson(github.event) }}"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ matrix.os }}-cargo-

      - run: cargo build --release --all-features --locked

      - name: Upload ${{ matrix.binary }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/BeeeQueue/nvm-rust/releases/${{ github.event.release.id }}/assets
          asset_path: ${{ matrix.binary }}
          asset_name: my-artifact.zip
          asset_content_type: application/octet-stream
